axios:
  timeout:      7000
port:           3000
auth:
  expireDays:   180 # 六个月不使用则用户身份过期
  cipher:       aes-256-cfb
term:
  # 目前可查询的各学期开学日期
  # 开学日期必须是周一
  17-18-1:      2017-8-28
  17-18-2:      2017-9-25
  17-18-3:      2018-2-26
  18-19-1:      2018-8-20
  18-19-2:      2018-9-17
spider:
  enable:       true
  port:         49034
  heartCycle:   40000
version:
  hybrid-kernel: 7
  android: 3
  androidApk: https://hybrid.myseu.cn/herald-app-beta-2.apk