axios:
  timeout:      7000
port:           3000
auth:
  expireDays:   180 # 六个月不使用则用户身份过期
  cipher:       aes-256-cfb
term:
  # 请务必即使添加个学期开学学期 关注教务处的发布的校历（5月底、6月初）
  # 目前可查询的各学期开学日期
  # 按照时间顺序
  # 开学日期必须是周一
  2017-2018-1:      2017-8-10 
  2017-2018-2:      2017-9-25
  2017-2018-3:      2018-2-26 
  2018-2019-1:      2018-8-20 
  2018-2019-2:      2018-9-17 
  2018-2019-3:      2019-2-25 
  2019-2020-1:      2019-8-19 
  2019-2020-2:      2019-9-16 
  2019-2020-3:      2020-2-24 
  2019-2020-4:      2020-8-31 
  2020-2021-1:      2020-9-28
  2020-2021-2:      2021-3-1
spider:
  enable:       true
  port:         49034
  heartCycle:   40000
version:
  hybrid-kernel: 29
  android: 6
  androidApk: https://hybrid.myseu.cn/herald-app-6.apk